name: Release

on:
  workflow_dispatch:
    branches: [master]
    inputs:
      notes:
        description: "Release Notes"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp build

      - name: Overwrite dosc folder with new build
        run: |
          cp docs/CNAME dist/CNAME
          rm -rf docs
          mv dist docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with: 
          branch: pre-release
          delete-branch: true
          title: ${{ github.event.inputs.notes }}        
